load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "gtest",
    sha256 = "b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5",
    strip_prefix = "googletest-release-1.11.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/release-1.11.0.tar.gz"],
)

http_archive(
    name = "benchmark",
    sha256 = "6132883bc8c9b0df5375b16ab520fac1a85dc9e4cf5be59480448ece74b278d4",
    strip_prefix = "benchmark-1.6.1",
    urls = ["https://github.com/google/benchmark/archive/refs/tags/v1.6.1.tar.gz"],
)

http_archive(
    name = "staq",
    build_file = "@//external_build:staq.BUILD",
    sha256 = "4887959389cbba0c8b54105eb006342bdfaaa53bb72db0ff465412423dfe9c26",
    strip_prefix = "staq-2.1",
    urls = ["https://github.com/softwareQinc/staq/archive/refs/tags/v2.1.tar.gz"],
)

http_archive(
    name = "moodycamel",
    build_file = "@//external_build:moodycamel.BUILD",
    sha256 = "eb37336bf9ae59aca7b954db3350d9b30d1cab24b96c7676f36040aa76e915e8",
    strip_prefix = "concurrentqueue-1.0.3",
    urls = ["https://github.com/cameron314/concurrentqueue/archive/refs/tags/v1.0.3.tar.gz"],
)

http_archive(
    name = "nlohmann_json",
    build_file = "@//external_build:nlohmann_json.BUILD",
    sha256 = "5daca6ca216495edf89d167f808d1d03c4a4d929cef7da5e10f135ae1540c7e4",
    strip_prefix = "json-3.10.5",
    urls = ["https://github.com/nlohmann/json/archive/refs/tags/v3.10.5.tar.gz"],
)

http_archive(
    name = "sparsepp",
    build_file = "@//external_build:sparsepp.BUILD",
    sha256 = "5516c814fe56c692aaa36f49e696f4a6292f04b5ae79f4ab7bd121e2cc48b917",
    strip_prefix = "sparsepp-1.22",
    urls = ["https://github.com/greg7mdp/sparsepp/archive/refs/tags/1.22.tar.gz"],
)
